### ISSUE TITLE
using 06-Fooocus can't view history images

### ISSUE THREAD

**Issue by dhlsam** [grokuku/stable-diffusion#18]
click histoy shows error
{"detail":"File not allowed: /config/outputs/06-Fooocus/2023-12-30/log.html."}

**Comment by grokuku** [comment]
Until I find why it is using this path, you'll have to replace "/config/outputs/06-Fooocus/" in the URL by "/config/06-Fooocus/Fooocus/outputs/"

In any case, if I'm not mistaken, this only shows the log for the current day. If you want to see past days, you can browse the output folder and open the log files manually (you don't need a web server to view them)

**Comment by grokuku** [comment]
I have a dirty workaround... 

You can edit the file webui.py and replace : 
`blocked_paths=[constants.AUTH_FILENAME]`
by : 
`blocked_paths=[constants.AUTH_FILENAME],
    allowed_paths=["/config/outputs/06-Fooocus"]`
    
found it here :
https://github.com/peterng1618/Fooocus/commit/78142a097dce201bb64d3854f2986857449ea1c8

**Comment by grokuku** [comment]
it looks like it's fixed in fooocus. 
So i'm closing this one :)
