### ISSUE TITLE
add ffmpeg ,transparent-background

### ISSUE THREAD

**Issue by xx2120** [grokuku/stable-diffusion#42]
Please put ffmpeg and the transparent-background, along with the corresponding ckpt_base.pth model, into a Docker container

**Comment by grokuku** [comment]
I'll add ffmpeg to the container, it's not big.
In the meantime, you should be able to install it manually using the two commands on the host (replace stable-diffusion with the name of your container) :
docker exec stable-diffusion /bin/apt-get update
docker exec stable-diffusion /bin/apt-get install ffmpeg -y

or directly on a cli inside the container :
apt-get update
apt-get install ffmpeg -y

For transparent-background can you tell me what it is ? 😵‍💫
Thanks :)

**Comment by grokuku** [comment]
ffmpeg is now available in the latest release.

**Comment by xx2120** [comment]
> ffmpeg is now available in the latest release.

thanks
