### ISSUE TITLE
forge runs once and crash at the next run

### ISSUE THREAD

**Issue by grokuku** [grokuku/stable-diffusion#45]
forge runs once and crash at the next run

**Comment by fabricemrchl** [comment]
Hi
Deleting file "Delete_this_file_to_clean_virtual_env_and_dependencies_at_next_launch" make forge running again.
I suppose it's related to dependencies.

**Comment by grokuku** [comment]
I'm closing this one since after cleaning env files it doesn't seems to crash anymore.
Thanks.
