### ISSUE TITLE
Start with --api

### ISSUE THREAD

**Issue by xer0-1ne** [grokuku/stable-diffusion#46]
Maybe I am missing something here, but I can't start with the --api flag.  When I add this to the "extra parameters" in Unraid, the container fails to build.

**Comment by grokuku** [comment]
Can you tell me with which webui you're trying ?

**Comment by xer0-1ne** [comment]
I am using A1111.  There was no parameters.txt, so I created one and added it.  

Additionally, I port forwarded 7860 as well, but I am still getting errors on trying to connect.
<img width="1248" alt="Screenshot 2024-05-03 at 11 48 51 AM" src="https://github.com/grokuku/stable-diffusion/assets/7335096/9ccb9644-6144-4774-abdc-ef30a518ed7b">
<img width="1168" alt="Screenshot 2024-05-03 at 11 49 43 AM" src="https://github.com/grokuku/stable-diffusion/assets/7335096/93317894-0948-46b2-8642-94fc044b353b">

**Comment by xer0-1ne** [comment]
The issue was me.  01-easy-diffusion isn't automatic1111.  Once I installed the right UI, everything worked perfectly.

**Comment by grokuku** [comment]
normally if the parameters.txt file is missing it should have created a new one with this content : 
`# Web + Network
--listen
--port 9000

# options
--enable-insecure-extension-access
--medvram
--xformers
--api

#--no-half-vae
#--disable-nan-check
#--update-all-extensions
#--reinstall-xformers
#--reinstall-torch`

the parameters under #Web + Network are important, don't forget to add them if you want to connect to the webui on the port 9000
