### ISSUE TITLE
A1111 and ForgeUI are broken

### ISSUE THREAD

**Issue by rjkruit** [grokuku/stable-diffusion#57]
After updating and after a clean install A111 and ForgeUI will fail to launch. It seems to be in a loop where it fails to start the  UI and download the dependencies.

**Comment by xikobe** [comment]
I'm having the same issue, some logs: 
```
/usr/bin/python3.10: No module named pip
Traceback (most recent call last):
  File "/config/02-sd-webui/forge/launch.py", line 51, in <module>
    main()
  File "/config/02-sd-webui/forge/launch.py", line 39, in main
    prepare_environment()
  File "/config/02-sd-webui/forge/modules/launch_utils.py", line 426, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "/config/02-sd-webui/forge/modules/launch_utils.py", line 125, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "/usr/bin/python3.10" -m pip install torch==2.1.2 torchvision==0.16.2 --extra-index-url https://download.pytorch.org/whl/cu121
Error code: 1
/02.forge.sh: line 74: wait: pid 99999 is not a child of this shell
/entry.sh: line 19: /02.forge: No such file or directory
/entry.sh: line 20: /config/scripts/02.forge: No such file or directory
/entry.sh: line 21: /config/scripts/02.forge.sh: No such file or directory
error when launching WebUI
```
I'm running on unraid

**Comment by Poag** [comment]
Based on the discussion here - https://forums.unraid.net/topic/143645-support-stable-diffusion-advanced/page/12/

python3-packaging python3-dev need adding, and the pip installation has gone awry. Insightface is also failing to auto install and must be manually installed.

**Comment by rbrinson** [comment]
I was having the exact same issue as @xikobe and the suggestion of manually installing `pip` worked for me as well. Hopefully, an updated image can resolve this.

**Comment by aurel-g** [comment]
In order not to have to do this manually after each launch, adding the command (`curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10`) at the beginning of /02-sd-webui/webui/webui-user.sh seems to work.

**Comment by Timboman** [comment]
The newest update to the docker that hit just a couple hours ago still has it broken sadly, plus it reset my changes to the webui-user.sh file, clearing it back to defaults.

**Comment by grokuku** [comment]
Sorry, it should be fixed in the most recent one now.

**Comment by aurel-g** [comment]
Yes, it's fixed in the latest image release.
