### ISSUE TITLE
How to use multiple Nvidia GPU card

### ISSUE THREAD

**Issue by phoenixxie0** [grokuku/stable-diffusion#58]
How to use multiple Nvidia GPU card

**Comment by grokuku** [comment]
I don't know what is your use case, but if you want to use multiple card you juste have to specify which card you want passed to the container with the NVIDIA_VISIBLE_DEVICES in you docker-compose fle or in your template if you use unraid.
if you want to pass all cards you can juste use the value "all" : 
NVIDIA_VISIBLE_DEVICES=0,2  (to pass cars 0 and 2)
NVIDIA_VISIBLE_DEVICES=all (to pass all cards)

Just to be sure, it isn't possible to use multple cards to render one image faster.
But I believe that with some webui (not all) it should be possible to split the render of a batch on multiple cards (but always one image per card)

**Comment by phoenixxie0** [comment]
Thx
