### ISSUE TITLE
Forge Option

### ISSUE THREAD

**Issue by buddylee7** [grokuku/stable-diffusion#68]
Thank you very much for your work and I like how you have made the install very versatile.  I was curious on how difficult it would be to have the Forge front end (Automatic 1111 Like) as it run the Comfy UI behind the scenes.

Also, if you could integrate LivePortrait as an option, would be fantastic!  :  https://github.com/KwaiVGI/LivePortrait

**Comment by buddylee7** [comment]
never mind, I just saw forge is an option but just not listed within the instructions when install via UNRAID!  TY!

**Comment by grokuku** [comment]
I didn't check the unraid template since a long time, sorry for the trouble ^^
