### ISSUE TITLE
webui 51 - Fcae Fusion is not working

### ISSUE THREAD

**Issue by aandy717** [grokuku/stable-diffusion#76]
Hi, I tried using WEBUI_VERSION 51 to test Face Fusion, but I'm encountering the following error:

python3: can't open file '/config/51-facefusion/facefusion/run.py': [Errno 2] No such file or directory
/51.sh: line 48: wait: pid 99999 is not a child of this shell
/entry.sh: line 19: /51: No such file or directory
/entry.sh: line 20: /config/scripts/51: No such file or directory
/entry.sh: line 21: /config/scripts/51.sh: No such file or directory
error when launching WebUI

**Comment by aurel-g** [comment]
Hi,

FaceFusion has made a small breaking change in version 3.0.0
run command and output directory option have to be adapted

I have submitted a PR (#77) with minimal changes so that FaceFusion can launch again.

**Comment by aandy717** [comment]
Thanks
